#!/bin/sh

set -e

REDIS_VERSION=redis-2.6.4

if [ ! -d "vendor" ]; then
    mkdir vendor
    pushd vendor
    if which wget > /dev/null; then
	wget http://redis.googlecode.com/files/$REDIS_VERSION.tar.gz
    else
	curl -O http://redis.googlecode.com/files/$REDIS_VERSION.tar.gz
    fi
    tar xvf $REDIS_VERSION.tar.gz
    pushd $REDIS_VERSION
    make
    popd
    popd
fi

if [ ! -d "config" ]; then
    mkdir config
    cp vendor/$REDIS_VERSION/redis.conf config/
fi

if [ ! -d "bin" ]; then
    mkdir bin
    cp vendor/$REDIS_VERSION/src/redis-server bin/
    cp vendor/$REDIS_VERSION/src/redis-cli bin/
fi
